### ISSUE TITLE
Planviz is overly sensitive to filenames

### ISSUE THREAD

**Issue by dcerys** [dollabs/planviz#42]
Planviz is overly sensitive to filenames

```
planviz -i edgect-htn-jan-2016.htn.edn=edgect-htn-jan-2016.tpn.edn 
16-Nov-28 14:24:29.435 nebbiolo ERROR [planviz.server:0] - error parsing plans: edgect-htn-jan-2016.htn.edn = edgect-htn-jan-2016.tpn.edn
16-Nov-28 14:24:29.453 nebbiolo ERROR [planviz.server:0] - HTN file not one of: ["edgect-htn-jan-2016.htn.edn" "edgect-htn-jan-2016.tpn.edn"]
```
However, the following (renaming the input  files) works fine:
```
planviz -i edgect.htn.edn=edgect.tpn.edn 
```
***However***, renaming the files in a different (slightly devious) way, results in a different problem:
```
planviz -i rightnow.htn.edn=rightnow.tpn.edn 
16-Nov-28 14:40:04.351 nebbiolo ERROR [planviz.server:0] - 
Unknown action: "rightnow.htn.edn=rightnow.tpn.edn". Must be one of: ("visualize" "save-config")
```

All that should matter is the end of the filename.  In the long-run, the JSON/EDN file should contain metadata that identifies the file as either an HTN or a TPN file.  In the short-run, only the suffix of the file should matter, where the file name format should be something like: *anything*.{tpn|htn}.{edn|json}

**Comment by tmarble** [comment]
The workaround of deriving a plan identifier from the input filename has been around
since it was discussed in the old BB issue 65. Both TPN's (starting with **:network-id**)
and HTN's (starting with **:network**) have top level objects that could (in the future) 
contain the plan instance id (removing the need to create a plan id from the filename).

In the meantime plan-schema (and thus planviz) should guess the plan type based
on the proper suffix _anything_.{tpn|htn}.{edn|json} (and not simply the occurrence
of the string tpn or htn elsewhere in the filename).
